### ISSUE TITLE
console.log doesn't work in ajaxer.html

### ISSUE THREAD

**Issue by tyler-hoffman** [power-cosmic/ajaxer#1]
``` javascript
ajaxer.get('moar_data.json', console.log);
```

gives me

``` javascript
TypeError: 'log' called on an object that does not implement interface Console.
```

in Firefox 40.0 and Nightly.

**Comment by pegurnee** [comment]
hey cool! Git commits messages saying "Fixes #X" closes the issue automatically.

**Comment by pegurnee** [comment]
It wasn't showing up in `Firefox 40` for me, but in `Chrome` and `Safarai` I had a similar issue. Passing anon function calling console.log solved it. Let me know if it is still an issue for you.

**Comment by tyler-hoffman** [comment]
Yeah, looks good. I'm confused about why the previous way doesn't work,
though.

**Comment by pegurnee** [comment]
It's the way that some browsers render those window constructs. Some of
them are treated as objects instead of type function which they should be.
Specifically noted Internet Explorer treats most of those window things as
objects and not functions, why Chrome follow IEs lead is beyond me.
